### PR TITLE
fix: remote URL querying of repos cloned using an SSH key

### LINKED ISSUE #120: fatal: unable to access <Git Repo URL>: The requested URL returned error: 400
With the new version 2.11, our github action is throwing a 400 error.

fatal: unable to access <Git Repo Url>: The requested URL returned error: 400

After we pinned the version to 2.9 it seem to work again.

repo-sync/pull-request@v2.9

### PR DESCRIPTION
**Pull request by m4heshd**
Fixes #120. 

A very thorough test is [available here](https://github.com/m4heshd/pr-action-test-ssh-clone/actions/runs/3863209096).

### CODE REVIEW

File: entrypoint.sh [hunk 1]
```diff
@@ -70,7 +70,7 @@ echo_info "DESTINATION_BRANCH=$DESTINATION_BRANCH"
 # Determine repository url
 if [[ -z "$INPUT_DESTINATION_REPOSITORY" ]]; then
   # Try to query local repository's remote url if INPUT_DESTINATION_REPOSITORY is null
-  local_origin=$(git remote get-url origin)
+  local_origin=$(git remote get-url origin | sed -E 's/:([^\/])/\/\1/g' | sed -e 's/ssh\/\/\///g' | sed -e 's/git@/https:\/\//g')
```
Comment (wei) [inline entrypoint.sh:73]: Thanks for the pr! Could you explain why we're using 3 sed?

What do you think about one Regex replace like https://gist.github.com/rsp/5ffd2c1f4e6278c58d47#file-git-change-url-L43

Comment (m4heshd) [reply entrypoint.sh]: It was something I picked up on SO and rushed to fix the issue. But ended up writing a much better sed script which lead to some cleanup as well. Changes were pushed and tested.
